USE `darties1` ;

/*SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;*/

CALL maj_dim_magasin_star();
CALL maj_faits_ventes_star();
CALL maj_securite_star();

CREATE OR REPLACE VIEW requete_enseigne AS
SELECT 0 AS CODE_ENSEIGNE, ID_ENSEIGNE
FROM dim_enseigne
UNION ALL
SELECT dim_enseigne.ID_ENSEIGNE as CODE_ENSEIGNE, dim_enseigne.ID_ENSEIGNE
FROM dim_enseigne;

CREATE OR REPLACE VIEW requete_famille AS
SELECT 0 AS CODE_FAMILLE, ID_FAMILLE_PRODUIT
FROM dim_famille_produit
UNION ALL
SELECT dim_famille_produit.ID_FAMILLE_PRODUIT as CODE_FAMILLE, dim_famille_produit.ID_FAMILLE_PRODUIT
FROM dim_famille_produit
ORDER BY 1;

CREATE OR REPLACE VIEW requete_geo AS
SELECT 0 AS CODE,ID_MAGASIN FROM dim_magasin
UNION
SELECT dim_geographique_com.ID_REGION_COM*100,ID_MAGASIN FROM dim_geographique_com,dim_magasin, dim_departement
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_com.ID_REGION_COM=dim_departement.ID_REGION_COM
UNION
SELECT dim_departement.ID_REGION_COM*100+ID_MAGASIN as CODE, ID_MAGASIN
FROM dim_geographique_com,dim_magasin, dim_departement
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_com.ID_REGION_COM=dim_departement.ID_REGION_COM
UNION
SELECT (DIM_GEOGRAPHIQUE_ADMIN.ID_REGION_ADMIN+9)*100 as CODE,ID_MAGASIN
FROM dim_geographique_admin,dim_departement,dim_magasin
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_admin.ID_REGION_ADMIN=dim_departement.ID_REGION_ADMIN1
AND dim_geographique_admin.ID_REGION_ADMIN<23
UNION
SELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100+ID_MAGASIN as CODE,ID_MAGASIN
FROM dim_geographique_admin,dim_departement,dim_magasin
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_admin.ID_REGION_ADMIN=dim_departement.ID_REGION_ADMIN1
AND dim_geographique_admin.ID_REGION_ADMIN<23
UNION
SELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100 as CODE, ID_MAGASIN
FROM dim_geographique_admin,dim_departement,dim_magasin
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_admin.ID_REGION_ADMIN=dim_departement.ID_REGION_ADMIN2
AND dim_geographique_admin.ID_REGION_ADMIN>=23
UNION
SELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100+ID_MAGASIN as CODE, ID_MAGASIN
FROM dim_geographique_admin,dim_departement,dim_magasin
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_admin.ID_REGION_ADMIN=dim_departement.ID_REGION_ADMIN2
AND dim_geographique_admin.ID_REGION_ADMIN>=23
ORDER BY 1;

CREATE OR REPLACE VIEW select_cumul(CODE, LIB_CUMUL) AS
SELECT 0 AS CODE,'Cumulé' AS LIB_CUMUL
UNION ALL
SELECT 1,'Non cumulé' ORDER BY 1;

CREATE OR REPLACE VIEW select_devise(CODE, LIB_devise) AS
SELECT ID_devise,LIB_devise from devise ORDER BY 1;

CREATE OR REPLACE VIEW select_enseigne(CODE, LIB_ENSEIGNE) AS
SELECT 0 AS CODE,'Toutes les enseignes' AS LIB_ENSEIGNE 
UNION ALL
SELECT dim_enseigne.ID_ENSEIGNE,dim_enseigne.LIB_ENSEIGNE FROM dim_enseigne
ORDER BY 1;

CREATE OR REPLACE VIEW select_famille_produit(CODE, LIB_FAMILLE) AS
SELECT 0 AS CODE,'Toutes les familles' AS LIB_FAMILLE
UNION ALL
SELECT ID_FAMILLE_PRODUIT, LIB_FAMILLE_PRODUIT FROM dim_famille_produit;

CREATE OR REPLACE VIEW select_indicateur(CODE, LIB_IND) AS
SELECT 0 as CODE, 'Tous les indicateurs' AS LIB_IND
UNION ALL
SELECT 1, 'Chiffres d''affaires' 
UNION ALL
SELECT 2, 'Nombres de ventes' 
UNION ALL
SELECT 3, 'Taux de marges' 
ORDER BY 1;

CREATE OR REPLACE VIEW select_onglet(CODE, LIB_ONGLET) AS
SELECT 1 AS CODE, 'Acceuil' AS LIB_ONGLET UNION ALL
SELECT 2, 'Historique' UNION ALL
SELECT 3, 'Palmarès' UNION ALL
SELECT 4, 'Détail' ORDER BY 1;

CREATE OR REPLACE VIEW select_user(CODE, USERNAME) AS
SELECT ID AS CODE, USERNAME FROM utilisateur
ORDER BY 1;

CREATE OR REPLACE VIEW select_zone_geo(CODE, LIBELLE) AS
SELECT 0 as CODE,'Toute la france' AS LIBELLE UNION ALL
SELECT dim_geographique_com.ID_REGION_COM*100 as CODE,LIB_REGION_COM as LIBELLE
FROM dim_geographique_com
UNION ALL
SELECT dim_departement.ID_REGION_COM*100+ID_MAGASIN as CODE, VILLE as LIBELLE
FROM dim_geographique_com,dim_magasin, dim_departement
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_com.ID_REGION_COM=dim_departement.ID_REGION_COM
UNION ALL
SELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100 as CODE,LIB_REGION_ADMIN as LIBELLE
FROM dim_geographique_admin
WHERE ID_REGION_ADMIN<23
UNION ALL
SELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100+ID_MAGASIN as CODE, VILLE as LIBELLE
FROM dim_geographique_admin,dim_departement,dim_magasin
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_admin.ID_REGION_ADMIN=dim_departement.ID_REGION_ADMIN1
AND dim_geographique_admin.ID_REGION_ADMIN<23
UNION ALL
SELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100 as CODE,LIB_REGION_ADMIN as LIBELLE
FROM dim_geographique_admin
WHERE ID_REGION_ADMIN>=23
UNION ALL
SELECT (dim_geographique_admin.ID_REGION_ADMIN+9)*100+ID_MAGASIN as CODE, VILLE as LIBELLE
FROM dim_geographique_admin,dim_departement,dim_magasin
WHERE dim_magasin.DEP=dim_departement.ID_DEPARTEMENT AND dim_geographique_admin.ID_REGION_ADMIN=dim_departement.ID_REGION_ADMIN2
AND dim_geographique_admin.ID_REGION_ADMIN>=23
ORDER BY CODE;

CREATE OR REPLACE VIEW select_temps AS 
SELECT CONCAT( cast( YEAR( NOW( ) ) AS char ) , '_1_', cast( YEAR( NOW( ) ) AS char ) ) AS CODE_TEMPS, cast( YEAR( NOW( ) ) AS char ) AS LIB_TEMPS, 19 AS ORDRE 
UNION ALL
SELECT CONCAT(ANNEE,'_4_',MOIS),CONCAT(' ',LIB_MOIS,' (',ANNEE,')'),MOIS from dim_temps 
WHERE ANNEE=YEAR(NOW()) AND CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad(MOIS, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
UNION ALL
SELECT DISTINCT CONCAT(ANNEE,'_3_',TRIMESTRE),CONCAT(' Trimestre ',TRIMESTRE,' (',ANNEE,')'),12+TRIMESTRE from dim_temps 
WHERE ANNEE=YEAR(NOW()) AND (CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((TRIMESTRE-1)*3+1, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((TRIMESTRE-1)*3+2, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((TRIMESTRE-1)*3+3, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
)
UNION ALL
SELECT DISTINCT CONCAT(ANNEE,'_2_',SEMESTRE),CONCAT(' Semestre ',SEMESTRE,' (',ANNEE,')'),16+SEMESTRE from dim_temps 
WHERE ANNEE=YEAR(NOW()) AND (CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((SEMESTRE-1)*6+1, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((SEMESTRE-1)*6+2, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((SEMESTRE-1)*6+3, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((SEMESTRE-1)*6+4, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((SEMESTRE-1)*6+5, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) ) AS char ),lpad((SEMESTRE-1)*6+6, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
)
UNION ALL
SELECT CONCAT( cast( YEAR( NOW( ) )-1 AS char ) , '_1_', cast( YEAR( NOW( ) )-1 AS char ) ) AS CODE_TEMPS, cast( YEAR( NOW( ) )-1 AS char ) AS LIB_TEMPS, 39 AS ORDRE 
UNION ALL
SELECT CONCAT(ANNEE,'_4_',MOIS),CONCAT(' ',LIB_MOIS,' (',ANNEE,')'),20+MOIS from dim_temps 
WHERE ANNEE=YEAR(NOW())-1 AND CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad(MOIS, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
UNION ALL
SELECT DISTINCT CONCAT(ANNEE,'_3_',TRIMESTRE),CONCAT(' Trimestre ',TRIMESTRE,' (',ANNEE,')'),32+TRIMESTRE from dim_temps 
WHERE ANNEE=YEAR(NOW())-1 AND (CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((TRIMESTRE-1)*3+1, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((TRIMESTRE-1)*3+2, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((TRIMESTRE-1)*3+3, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
)
UNION ALL
SELECT DISTINCT CONCAT(ANNEE,'_2_',SEMESTRE),CONCAT(' Semestre ',SEMESTRE,' (',ANNEE,')'),36+SEMESTRE from dim_temps 
WHERE ANNEE=YEAR(NOW())-1 AND (CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((SEMESTRE-1)*6+1, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((SEMESTRE-1)*6+2, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((SEMESTRE-1)*6+3, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((SEMESTRE-1)*6+4, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((SEMESTRE-1)*6+5, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) )-1 AS char ),lpad((SEMESTRE-1)*6+6, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
)
UNION ALL
SELECT CONCAT( cast( YEAR( NOW( ) )-2 AS char ) , '_1_', cast( YEAR( NOW( ) )-2 AS char ) ) AS CODE_TEMPS, cast( YEAR( NOW( ) )-2 AS char ) AS LIB_TEMPS, 59 AS ORDRE 
UNION ALL
SELECT CONCAT(ANNEE,'_4_',MOIS),CONCAT(' ',LIB_MOIS,' (',ANNEE,')'),40+MOIS from dim_temps 
WHERE ANNEE=YEAR(NOW())-2 AND CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad(MOIS, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
UNION ALL
SELECT DISTINCT CONCAT(ANNEE,'_3_',TRIMESTRE),CONCAT(' Trimestre ',TRIMESTRE,' (',ANNEE,')'),52+TRIMESTRE from dim_temps 
WHERE ANNEE=YEAR(NOW())-2 AND (CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((TRIMESTRE-1)*3+1, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((TRIMESTRE-1)*3+2, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((TRIMESTRE-1)*3+3, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
)
UNION ALL
SELECT DISTINCT CONCAT(ANNEE,'_2_',SEMESTRE),CONCAT(' Semestre ',SEMESTRE,' (',ANNEE,')'),56+SEMESTRE from dim_temps 
WHERE ANNEE=YEAR(NOW())-2 AND (CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((SEMESTRE-1)*6+1, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((SEMESTRE-1)*6+2, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((SEMESTRE-1)*6+3, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((SEMESTRE-1)*6+4, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null) 
OR CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((SEMESTRE-1)*6+5, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
OR CONCAT( cast( YEAR( NOW( ) )-2 AS char ),lpad((SEMESTRE-1)*6+6, 2, 0)) IN (SELECT DISTINCT ID_TEMPS FROM faits_ventes_star where CA_REEL is not null)
)
ORDER BY 3;


CREATE TABLE IF NOT EXISTS dwr_faits_ventes ENGINE=InnoDB DEFAULT CHARACTER SET = utf8 COMMENT ='Analyse croisee des faits' AS
SELECT ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , 'VENTES' AS INDICATEUR , SUM(VENTES_OBJECTIF) AS OBJECTIF , SUM(VENTES_REEL)AS REEL,NULL AS DATE_MAJ
FROM faits_ventes
GROUP BY ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS, DATE_MAJ
UNION ALL
SELECT ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , 'CA' AS INDICATEUR , SUM(CA_OBJECTIF) AS OBJECTIF , SUM(CA_REEL)AS REEL,NULL AS DATE_MAJ
FROM faits_ventes
GROUP BY ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , DATE_MAJ
UNION ALL
SELECT ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , 'MARGE' AS INDICATEUR , AVG(MARGE_OBJECTIF) AS OBJECTIF , AVG(MARGE_REEL) AS REEL,NULL AS DATE_MAJ
FROM faits_ventes
GROUP BY ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , DATE_MAJ
ORDER by 1,2,3,4
;
ALTER TABLE dwr_faits_ventes ADD CONSTRAINT PK_dwr_faits_ventes PRIMARY KEY (ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS,INDICATEUR);

DELIMITER |
CREATE PROCEDURE maj_dwr_faits_ventes()
BEGIN
	TRUNCATE dwr_faits_ventes;
    INSERT INTO dwr_faits_ventes
    SELECT ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , 'VENTES' AS INDICATEUR , SUM(VENTES_OBJECTIF) AS OBJECTIF , SUM(VENTES_REEL)AS REEL,NULL AS DATE_MAJ
    FROM faits_ventes
    GROUP BY ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS, DATE_MAJ
    UNION ALL
    SELECT ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , 'CA' AS INDICATEUR , SUM(CA_OBJECTIF) AS OBJECTIF , SUM(CA_REEL)AS REEL,NULL AS DATE_MAJ
    FROM faits_ventes
    GROUP BY ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , DATE_MAJ
    UNION ALL
    SELECT ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , 'MARGE' AS INDICATEUR , AVG(MARGE_OBJECTIF) AS OBJECTIF , AVG(MARGE_REEL) AS REEL,NULL AS DATE_MAJ
    FROM faits_ventes
    GROUP BY ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS , DATE_MAJ
    ORDER by 1,2,3,4
    ;
END |
DELIMITER ;

CALL maj_dwr_faits_ventes();




#donnees temporelles non cumulées SELECT_CUMUL=1 : requete_temps_1
#donnees temporelles cumulées SELECT_CUMUL=0 : requete_temps_0
# une requete peut etre : SELECT * FROM requete_temps_1 WHERE @SELECT_CUMUL=1 UNION ALL SELECT * FROM requete_temps_0 WHERE @SELECT_CUMUL=0;
 
CREATE OR REPLACE VIEW requete_temps_1 AS 
SELECT CONCAT( cast( YEAR( NOW( ) ) AS char ) , '_1_', cast( YEAR( NOW( ) ) AS char ) ) AS CODE,ID_TEMPS AS ID_TEMPS FROM dim_temps WHERE ANNEE=YEAR(NOW()) 
UNION ALL
SELECT concat(ANNEE,'_4_',MOIS),  ID_TEMPS from dim_temps 
WHERE ANNEE=YEAR(NOW())
UNION ALL
SELECT DISTINCT ANNEE||'_3_'||TRIMESTRE,ID_TEMPS from dim_temps T1
WHERE ANNEE=YEAR(NOW()) AND MOIS IN (SELECT DISTINCT MOIS FROM dim_temps WHERE ANNEE=T1.ANNEE AND TRIMESTRE=T1.TRIMESTRE) 
UNION ALL
SELECT DISTINCT ANNEE||'_2_'||SEMESTRE, ID_TEMPS from dim_temps T1 
WHERE ANNEE=YEAR(NOW()) AND MOIS IN (SELECT DISTINCT MOIS FROM dim_temps WHERE ANNEE=T1.ANNEE AND SEMESTRE=T1.SEMESTRE) 
UNION ALL
SELECT CONCAT( cast( YEAR( NOW( ) )-1 AS char ) , '_1_', cast( YEAR( NOW( ) )-1 AS char ) ) AS CODE,ID_TEMPS AS ID_TEMPS FROM dim_temps WHERE ANNEE=YEAR(NOW())-1 
UNION ALL
SELECT concat(ANNEE,'_4_',MOIS),  ID_TEMPS from dim_temps 
WHERE ANNEE=YEAR(NOW())-1
UNION ALL
SELECT DISTINCT ANNEE||'_3_'||TRIMESTRE,ID_TEMPS from dim_temps T1
WHERE ANNEE=YEAR(NOW())-1 AND MOIS IN (SELECT DISTINCT MOIS FROM dim_temps WHERE ANNEE=T1.ANNEE AND TRIMESTRE=T1.TRIMESTRE) 
UNION ALL
SELECT DISTINCT ANNEE||'_2_'||SEMESTRE, ID_TEMPS from dim_temps T1 
WHERE ANNEE=YEAR(NOW())-1 AND MOIS IN (SELECT DISTINCT MOIS FROM dim_temps WHERE ANNEE=T1.ANNEE AND SEMESTRE=T1.SEMESTRE) 
UNION ALL
SELECT CONCAT( cast( YEAR( NOW( ) )-2 AS char ) , '_1_', cast( YEAR( NOW( ) )-2 AS char ) ) AS CODE,ID_TEMPS AS ID_TEMPS FROM dim_temps WHERE ANNEE=YEAR(NOW())-2 
UNION ALL
SELECT concat(ANNEE,'_4_',MOIS),  ID_TEMPS from dim_temps 
WHERE ANNEE=YEAR(NOW())-2
UNION ALL
SELECT DISTINCT ANNEE||'_3_'||TRIMESTRE,ID_TEMPS from dim_temps T1
WHERE ANNEE=YEAR(NOW())-2 AND MOIS IN (SELECT DISTINCT MOIS FROM dim_temps WHERE ANNEE=T1.ANNEE AND TRIMESTRE=T1.TRIMESTRE) 
UNION ALL
SELECT DISTINCT ANNEE||'_2_'||SEMESTRE, ID_TEMPS from dim_temps T1 
WHERE ANNEE=YEAR(NOW())-2 AND MOIS IN (SELECT DISTINCT MOIS FROM dim_temps WHERE ANNEE=T1.ANNEE AND SEMESTRE=T1.SEMESTRE) 
;

CREATE OR REPLACE VIEW requete_temps_0 AS 
SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2) AS CODE,CONCAT(YEAR(NOW())-2,'01') AS ID_TEMPS
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_1_',YEAR(NOW())-2),CONCAT(YEAR(NOW())-2,'12')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_1'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_1'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_1'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_1'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_1'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_1'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_2_2'),CONCAT(YEAR(NOW())-2,'12')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_1'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_1'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_1'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_2'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_2'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_2'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_2'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_2'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_2'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_3'),CONCAT(YEAR(NOW())-2,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_3_4'),CONCAT(YEAR(NOW())-2,'12')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_1'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_10'),CONCAT(YEAR(NOW())-2,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_11'),CONCAT(YEAR(NOW())-2,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_12'),CONCAT(YEAR(NOW())-2,'12')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_2'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_2'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_3'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_3'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_3'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_4'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_4'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_4'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_4'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_5'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_5'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_5'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_5'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_5'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_6'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_6'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_6'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_6'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_6'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_6'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_7'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_7'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_7'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_7'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_7'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_7'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_7'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_8'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_8'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_8'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_8'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_8'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_8'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_8'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_8'),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-2,'_4_9'),CONCAT(YEAR(NOW())-2,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_1_',YEAR(NOW())-1),CONCAT(YEAR(NOW())-1,'12')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_1'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_1'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_1'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_1'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_1'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_1'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_2_2'),CONCAT(YEAR(NOW())-1,'12')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_1'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_1'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_1'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_2'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_2'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_2'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_2'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_2'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_2'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_3'),CONCAT(YEAR(NOW())-1,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_3_4'),CONCAT(YEAR(NOW())-1,'12')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_1'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_10'),CONCAT(YEAR(NOW())-1,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_11'),CONCAT(YEAR(NOW())-1,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'09')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'10')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'11')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_12'),CONCAT(YEAR(NOW())-1,'12')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_2'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_2'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_3'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_3'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_3'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_4'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_4'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_4'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_4'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_5'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_5'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_5'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_5'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_5'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_6'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_6'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_6'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_6'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_6'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_6'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_7'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_7'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_7'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_7'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_7'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_7'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_7'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_8'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_8'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_8'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_8'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_8'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_8'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_8'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_8'),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'01')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'02')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'03')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'04')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'05')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'06')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'07')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'08')
UNION ALL SELECT CONCAT(YEAR(NOW())-1,'_4_9'),CONCAT(YEAR(NOW())-1,'09')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'09')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'10')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'11')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_1_',YEAR(NOW())),CONCAT(YEAR(NOW()),'12')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_1'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_1'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_1'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_1'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_1'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_1'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'09')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'10')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'11')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_2_2'),CONCAT(YEAR(NOW()),'12')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_1'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_1'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_1'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_2'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_2'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_2'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_2'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_2'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_2'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_3'),CONCAT(YEAR(NOW()),'09')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'09')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'10')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'11')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_3_4'),CONCAT(YEAR(NOW()),'12')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_1'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'09')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_10'),CONCAT(YEAR(NOW()),'10')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'09')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'10')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_11'),CONCAT(YEAR(NOW()),'11')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'09')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'10')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'11')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_12'),CONCAT(YEAR(NOW()),'12')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_2'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_2'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_3'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_3'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_3'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_4'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_4'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_4'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_4'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_5'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_5'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_5'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_5'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_5'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_6'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_6'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_6'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_6'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_6'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_6'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_7'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_7'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_7'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_7'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_7'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_7'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_7'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_8'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_8'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_8'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_8'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_8'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_8'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_8'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_8'),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'01')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'02')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'03')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'04')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'05')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'06')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'07')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'08')
UNION ALL SELECT CONCAT(YEAR(NOW()),'_4_9'),CONCAT(YEAR(NOW()),'09')
;

select * from dim_temps where mois IN(2,8,12);
-- accents problematiques en decembre, aout, février 
update dim_temps set lib_mois='décembre' where mois=12;
update dim_temps set lib_mois='février' where mois=2;
update dim_temps set lib_mois='août' where mois=8;

select * from dim_temps where mois IN(2,8,12);
# exemples de rapport dans MySQL
SET @SELECT_CUMUL=0;
SELECT COUNT(*) FROM (SELECT * FROM requete_temps_1 WHERE @SELECT_CUMUL=1 UNION ALL SELECT * FROM requete_temps_0 WHERE @SELECT_CUMUL=0) AS T1;
SET @SELECT_CUMUL=1;
SELECT COUNT(*) FROM (SELECT * FROM requete_temps_1 WHERE @SELECT_CUMUL=1 UNION ALL SELECT * FROM requete_temps_0 WHERE @SELECT_CUMUL=0) AS T1;

SET @SELECT_CUMUL=1;
SET @SELECT_COURS=1;
SET @SELECT_USER=2;
SET @SELECT_INDICATEUR=1;
SET @SELECT_FAMILLE_PRODUIT=0;
SET @SELECT_ENSEIGNE=0;
SET @SELECT_ONGLET=1;
SET @SELECT_ZONE_GEO=0;
SET @SELECT_DEVISE=1;
SET @SELECT_TEMPS='2015_1_2015';
select *
from faits_ventes
where faits_ventes.id_magasin in (select id_magasin from utilisateur,securite,profil where utilisateur.id_profil=profil.id_profil and utilisateur.id=@SELECT_USER and profil.id_profil=securite.id_profil and securite.onglet=@SELECT_ONGLET) 
;

select sum(ca_reel)*@SELECT_cours as ca_reel
from faits_ventes
where faits_ventes.id_magasin in (select id_magasin from utilisateur,securite,profil where utilisateur.id_profil=profil.id_profil and utilisateur.id=@SELECT_USER and profil.id_profil=securite.id_profil and securite.onglet=@SELECT_ONGLET) 
and faits_ventes.id_magasin in (select id_magasin from requete_geo where code=@SELECT_ZONE_GEO)
and faits_ventes.id_temps in (select id_temps from (SELECT id_temps FROM requete_temps_1 WHERE @SELECT_CUMUL=1 and code=@SELECT_TEMPS UNION ALL SELECT id_temps FROM requete_temps_0 WHERE @SELECT_CUMUL=0 AND code=@SELECT_TEMPS) AS requete_temps)
and faits_ventes.id_famille_produit in (select id_famille_produit from requete_famille where code_famille=@SELECT_FAMILLE_PRODUIT)
and faits_ventes.id_magasin in (select id_magasin from dim_magasin where id_enseigne in (select id_enseigne from requete_enseigne where code_enseigne=@SELECT_ENSEIGNE))
;

SET @ID_SESSION_PHP='123456789';

DROP TABLE IF EXISTS data;

CREATE TABLE IF NOT EXISTS data ENGINE=InnoDB DEFAULT CHARACTER SET = utf8 COMMENT ='Analyse croisee suite' AS
SELECT DISTINCT
dwr_faits_ventes.ID_MAGASIN, 
dwr_faits_ventes.ID_FAMILLE_PRODUIT,
dwr_faits_ventes.ID_TEMPS, 
dwr_faits_ventes.INDICATEUR, 
dwr_faits_ventes.OBJECTIF,
dwr_faits_ventes.REEL, 
dwr_faits_ventes.DATE_MAJ, 
dim_famille_produit.LIB_FAMILLE_PRODUIT, 
dim_famille_produit.DATEMAJ_FAMPROD,
dim_magasin.ID_ENSEIGNE, 
dim_magasin.ACTIF, 
dim_magasin.DATE_OUVERTURE,
dim_magasin.DATE_FERMETURE, 
dim_magasin.DATE_MAJ AS DATE_MAJ_MAG, 
dim_magasin.EMPLACEMENTS,
dim_magasin.NB_CAISSES, 
dim_magasin.VILLE, 
dim_magasin.DEP,
dim_magasin.FICHIER_IMAGE_CARTE_MAGASIN, 
securite.ONGLET, 
securite.DATEMAJ_SECURITE, 
profil.ID_PROFIL, 
profil.LIB_PROFIL,
profil.TYPE_ZONE, 
profil.ID_ZONE, 
profil.USERNAME_BO, 
profil.PASSWORD_BO, 
profil.DATEMAJ_PROFIL,
utilisateur.ID, 
utilisateur.NOM, 
utilisateur.PRENOM, 
utilisateur.USERNAME, 
utilisateur.PASSWORD,
utilisateur.MAIL, 
utilisateur.DATEMAJ_USER, 
dim_enseigne.LIB_ENSEIGNE, 
dim_enseigne.FICHIER_IMAGE_LOGO_ENSEIGNE,
dim_enseigne.DATEMAJ_ENSEIGNE, 
dim_departement.ID_DEPARTEMENT, 
dim_departement.CODE_DEPARTEMENT,
dim_departement.LIB_DEPARTEMENT, 
dim_departement.ID_REGION_ADMIN1,
dim_departement.ID_REGION_ADMIN2, 
dim_departement.ID_REGION_COM, 
dim_departement.DATEMAJ_DEP
FROM dwr_faits_ventes INNER JOIN dim_famille_produit ON dwr_faits_ventes.ID_FAMILLE_PRODUIT=dim_famille_produit.ID_FAMILLE_PRODUIT
INNER JOIN dim_magasin ON dwr_faits_ventes.id_magasin=dim_magasin.id_magasin
INNER JOIN securite ON dwr_faits_ventes.id_magasin=securite.id_magasin
INNER JOIN profil ON securite.id_profil=profil.id_profil
INNER JOIN utilisateur ON profil.id_profil=utilisateur.id_profil
INNER JOIN dim_enseigne ON dim_magasin.id_enseigne=dim_enseigne.id_enseigne
INNER JOIN dim_departement ON dim_magasin.dep=dim_departement.id_departement
;

ALTER TABLE data ADD CONSTRAINT PK_data PRIMARY KEY (ID_MAGASIN , ID_FAMILLE_PRODUIT , ID_TEMPS,INDICATEUR, ID_PROFIL);
;

SELECT COUNT(*) FROM dwr_faits_ventes;
SELECT COUNT(*) FROM data;

DELIMITER |
CREATE PROCEDURE maj_data()
BEGIN
	TRUNCATE data;
    INSERT INTO data
	SELECT 
	dwr_faits_ventes.ID_MAGASIN, 
	dwr_faits_ventes.ID_FAMILLE_PRODUIT,
	dwr_faits_ventes.ID_TEMPS, 
	dwr_faits_ventes.INDICATEUR, 
	dwr_faits_ventes.OBJECTIF,
	dwr_faits_ventes.REEL, 
	dwr_faits_ventes.DATE_MAJ, 
	dim_famille_produit.LIB_FAMILLE_PRODUIT, 
	dim_famille_produit.DATEMAJ_FAMPROD,
	dim_magasin.ID_ENSEIGNE, 
	dim_magasin.ACTIF, 
	dim_magasin.DATE_OUVERTURE,
	dim_magasin.DATE_FERMETURE, 
	dim_magasin.DATE_MAJ AS DATE_MAJ_MAG, 
	dim_magasin.EMPLACEMENTS,
	dim_magasin.NB_CAISSES, 
	dim_magasin.VILLE, 
	dim_magasin.DEP,
	dim_magasin.FICHIER_IMAGE_CARTE_MAGASIN, 
	securite.ONGLET, 
	securite.DATEMAJ_SECURITE, 
	profil.ID_PROFIL, 
	profil.LIB_PROFIL,
	profil.TYPE_ZONE, 
	profil.ID_ZONE, 
	profil.USERNAME_BO, 
	profil.PASSWORD_BO, 
	profil.DATEMAJ_PROFIL,
	utilisateur.ID, 
	utilisateur.NOM, 
	utilisateur.PRENOM, 
	utilisateur.USERNAME, 
	utilisateur.PASSWORD,
	utilisateur.MAIL, 
	utilisateur.DATEMAJ_USER, 
	dim_enseigne.LIB_ENSEIGNE, 
	dim_enseigne.FICHIER_IMAGE_LOGO_ENSEIGNE,
	dim_enseigne.DATEMAJ_ENSEIGNE, 
	dim_departement.ID_DEPARTEMENT, 
	dim_departement.CODE_DEPARTEMENT,
	dim_departement.LIB_DEPARTEMENT, 
	dim_departement.ID_REGION_ADMIN1,
	dim_departement.ID_REGION_ADMIN2, 
	dim_departement.ID_REGION_COM, 
	dim_departement.DATEMAJ_DEP
	FROM dwr_faits_ventes INNER JOIN dim_famille_produit ON dwr_faits_ventes.ID_FAMILLE_PRODUIT=dim_famille_produit.ID_FAMILLE_PRODUIT
	INNER JOIN dim_magasin ON dwr_faits_ventes.id_magasin=dim_magasin.id_magasin
	INNER JOIN securite ON dwr_faits_ventes.id_magasin=securite.id_magasin
	INNER JOIN profil ON securite.id_profil=profil.id_profil
	INNER JOIN utilisateur ON profil.id_profil=utilisateur.id_profil
	INNER JOIN dim_enseigne ON dim_magasin.id_enseigne=dim_enseigne.id_enseigne
	INNER JOIN dim_departement ON dim_magasin.dep=dim_departement.id_departement
	;    
END |
DELIMITER ;

CALL maj_data();

CREATE OR REPLACE VIEW data_0 AS
SELECT 
select_temps.CODE_TEMPS, 
select_temps.LIB_TEMPS, 
select_temps.ORDRE,
requete_temps_0.CODE, 
data.ID_MAGASIN, 
data.ID_FAMILLE_PRODUIT,
data.ID_TEMPS, 
data.INDICATEUR, 
data.OBJECTIF, 
data.REEL, 
data.DATE_MAJ,
data.LIB_FAMILLE_PRODUIT, 
data.DATEMAJ_FAMPROD, 
data.ID_ENSEIGNE, 
data.ACTIF,
data.DATE_OUVERTURE, 
data.DATE_FERMETURE, 
data.DATE_MAJ_MAG, 
data.EMPLACEMENTS, 
data.NB_CAISSES,
data.VILLE, 
data.DEP, 
data.FICHIER_IMAGE_CARTE_MAGASIN, 
data.ONGLET, 
data.DATEMAJ_SECURITE,
data.ID_PROFIL, 
data.LIB_PROFIL, 
data.TYPE_ZONE, 
data.ID_ZONE, 
data.USERNAME_BO,
data.PASSWORD_BO, 
data.DATEMAJ_PROFIL, 
data.ID, 
data.NOM, 
data.PRENOM, 
data.USERNAME,
data.PASSWORD, 
data.MAIL, 
data.DATEMAJ_USER, 
data.LIB_ENSEIGNE,
data.FICHIER_IMAGE_LOGO_ENSEIGNE, 
data.DATEMAJ_ENSEIGNE, 
data.ID_DEPARTEMENT,
data.CODE_DEPARTEMENT, 
data.LIB_DEPARTEMENT, 
data.ID_REGION_ADMIN1, 
data.ID_REGION_ADMIN2,
data.ID_REGION_COM, 
data.DATEMAJ_DEP,
SUBSTR(data.ID_TEMPS,1,4) AS ANNEE,
SUBSTR(data.ID_TEMPS,5,2) AS MOIS,
CASE INDICATEUR
WHEN 'CA' THEN 1
WHEN 'VENTES' THEN 2
WHEN 'MARGE' THEN 3
ELSE 0
END AS id_i
FROM select_temps
INNER JOIN requete_temps_0 ON select_temps.CODE_TEMPS=requete_temps_0.code
INNER JOIN data ON data.ID_TEMPS=requete_temps_0.ID_TEMPS
;

SELECT COUNT(*) FROM data_0;

CREATE OR REPLACE VIEW data_1 AS
SELECT 
select_temps.CODE_TEMPS, 
select_temps.LIB_TEMPS, 
select_temps.ORDRE,
requete_temps_1.CODE, 
data.ID_MAGASIN, 
data.ID_FAMILLE_PRODUIT,
data.ID_TEMPS, 
data.INDICATEUR, 
data.OBJECTIF, 
data.REEL, 
data.DATE_MAJ,
data.LIB_FAMILLE_PRODUIT, 
data.DATEMAJ_FAMPROD, 
data.ID_ENSEIGNE, 
data.ACTIF,
data.DATE_OUVERTURE, 
data.DATE_FERMETURE, 
data.DATE_MAJ_MAG, 
data.EMPLACEMENTS, 
data.NB_CAISSES,
data.VILLE, 
data.DEP, 
data.FICHIER_IMAGE_CARTE_MAGASIN, 
data.ONGLET, 
data.DATEMAJ_SECURITE,
data.ID_PROFIL, 
data.LIB_PROFIL, 
data.TYPE_ZONE, 
data.ID_ZONE, 
data.USERNAME_BO,
data.PASSWORD_BO, 
data.DATEMAJ_PROFIL, 
data.ID, 
data.NOM, 
data.PRENOM, 
data.USERNAME,
data.PASSWORD, 
data.MAIL, 
data.DATEMAJ_USER, 
data.LIB_ENSEIGNE,
data.FICHIER_IMAGE_LOGO_ENSEIGNE, 
data.DATEMAJ_ENSEIGNE, 
data.ID_DEPARTEMENT,
data.CODE_DEPARTEMENT, 
data.LIB_DEPARTEMENT, 
data.ID_REGION_ADMIN1, 
data.ID_REGION_ADMIN2,
data.ID_REGION_COM, 
data.DATEMAJ_DEP,
SUBSTR(data.ID_TEMPS,1,4) AS ANNEE,
SUBSTR(data.ID_TEMPS,5,2) AS MOIS,
CASE INDICATEUR
WHEN 'CA' THEN 1
WHEN 'VENTES' THEN 2
WHEN 'MARGE' THEN 3
ELSE 0
END AS id_i
FROM select_temps
INNER JOIN requete_temps_1 ON select_temps.CODE_TEMPS=requete_temps_1.code
INNER JOIN data ON data.ID_TEMPS=requete_temps_1.ID_TEMPS
;

SELECT COUNT(*) FROM data_1;


